name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: jeetkansagra07/monorepo-cicd-backend:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.201.4.224
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           docker stop user_backend 2>/dev/null || true
           docker rm user_backend 2>/dev/null || true
           docker run --name user_backend -d -p 8080:8080 jeetkansagra07/monorepo-cicd-backend:${{ github.sha }}
